import type { ConsoleSnapshot } from "./types";

export const demoSnapshot: ConsoleSnapshot = {
  mode: "demo",
  backendStatus: "warning",
  generatedAt: "2026-05-05T00:00:00.000Z",
  project: {
    id: "moyuan-code",
    name: "moyuan-code",
    root: "/home/tiammomo/projects/dev/moyuan-code",
    status: "planning-ready",
    source: { provider: "github", url: "git@github.com:tiammomo/moyuan-code.git" },
  },
  stats: {
    issues: 7,
    accepted: 4,
    blocked: 1,
    providers: 5,
    resources: 2,
    deployments: 1,
    executions: 2,
    runs: 2,
    recoveries: 1,
    visual_assets: 1,
    visual_render_executions: 1,
    control_loop_runs: 1,
    batch_plans: 1,
    batch_runs: 1,
    worktrees: 1,
    merge_queues: 1,
    integration_previews: 1,
    integration_applies: 1,
    release_batches: 1,
    release_candidates: 1,
  },
  issues: [
    {
      id: "req-clarify",
      title: "需求澄清与 Issue Graph",
      role: "requirement_refiner",
      status: "accepted",
      runtime: "claude_cli",
      provider: "claude_cli",
      quality: "accepted",
      lane: "plan",
    },
    {
      id: "api-contract",
      title: "控制面 API 契约",
      role: "architect",
      status: "accepted",
      depends_on: ["req-clarify"],
      runtime: "claude_cli",
      provider: "claude_cli",
      quality: "accepted",
      lane: "plan",
    },
    {
      id: "backend-state-api",
      title: "Gin/GORM 状态 API",
      role: "backend",
      status: "accepted",
      depends_on: ["api-contract"],
      runtime: "codex_cli",
      provider: "codex_cli",
      quality: "passed",
      lane: "backend",
    },
    {
      id: "frontend-console",
      title: "Next.js 16 Console",
      role: "frontend",
      status: "running",
      depends_on: ["api-contract"],
      run_id: "run-frontend-console",
      subagent_id: "subagent-frontend-console",
      runtime: "claude_cli",
      runtime_status: "completed",
      provider: "minimax-m27-claude",
      quality: "passed",
      quality_report_id: "quality-frontend-console",
      quality_decision: "QUALITY_ACCEPTED",
      quality_reasons: ["quality_and_review_accepted"],
      review_status: "accepted",
      skills: ["grill-me", "tdd"],
      output_contract: ["diff_summary", "test_evidence", "review_notes"],
      lane: "frontend",
    },
    {
      id: "quality-review",
      title: "Diff-first Review",
      role: "quality_guard",
      status: "waiting",
      depends_on: ["backend-state-api", "frontend-console"],
      run_id: "run-quality-review",
      subagent_id: "subagent-quality-review",
      runtime: "codex_cli",
      runtime_status: "running",
      provider: "codex_cli",
      quality: "pending",
      quality_report_id: "quality-review-pending",
      quality_decision: "QUALITY_PENDING",
      quality_reasons: ["waiting_for_frontend_diff"],
      review_status: "pending",
      blocked_reason: "waiting_frontend_decision",
      skills: ["diagnose"],
      output_contract: ["blocking_findings", "merge_decision"],
      lane: "quality",
    },
    {
      id: "release-suggest",
      title: "Release Suggestion",
      role: "release_manager",
      status: "ready",
      depends_on: ["quality-review"],
      runtime: "codex_cli",
      provider: "codex_cli",
      lane: "release",
    },
    {
      id: "deploy-plan",
      title: "Deploy / Smoke / Monitor",
      role: "devops",
      status: "blocked",
      depends_on: ["release-suggest"],
      blocked_reason: "production_approval_required",
      lane: "release",
    },
  ],
  schedule: [
    { issue_id: "frontend-console", status: "dispatch", runtime_id: "claude_cli" },
    { issue_id: "quality-review", status: "waiting", runtime_id: "codex_cli", blocked_reason: "waiting_frontend_decision" },
    { issue_id: "deploy-plan", status: "blocked", runtime_id: "codex_cli", blocked_reason: "production_approval_required" },
  ],
  subagent_backlog: [
    {
      issue_id: "quality-review",
      subagent_id: "subagent-quality-review",
      status: "retrying",
      reason: "runtime_failed",
      recovery_id: "recovery-run-quality-review-codex-cli",
      failure_category: "runtime_failed",
      retry_count: 1,
      max_retries: 2,
    },
  ],
  providers: [
    {
      id: "minimax-m27-claude",
      name: "MiniMax M2.7 via Claude CLI",
      vendor: "minimax",
      api_type: "anthropic-compatible",
      enabled: true,
      runtime_id: "claude_cli",
      model: "MiniMax-M2.7",
      use_cases: ["frontend", "planning", "review"],
      health_status: "ok",
      quota_status: "ok",
      cost_status: "warning",
    },
    {
      id: "codex_cli",
      name: "Codex CLI",
      vendor: "openai",
      api_type: "codex_cli",
      enabled: true,
      runtime_id: "codex_cli",
      use_cases: ["backend", "testing", "review", "repair"],
      health_status: "ok",
    },
    {
      id: "gpt_image_2",
      name: "GPT Image 2",
      vendor: "openai",
      api_type: "image",
      enabled: false,
      model: "gpt-image-2",
      use_cases: ["architecture_diagram"],
      health_status: "unknown",
    },
  ],
  provider_telemetry: [
    {
      id: "provider-telemetry-minimax",
      provider_id: "minimax-m27-claude",
      source: "ops_refresh",
      decision: "PROVIDER_TELEMETRY_WARNING",
      reason: "provider_degraded_or_budget_warning",
      health_status: "ok",
      quota_status: "ok",
      cost_status: "warning",
      usage_tokens: 18400,
      estimated_cost: 4.2,
      created_at: "2026-05-05T00:30:00.000Z",
    },
  ],
  resources: [
    {
      id: "dev-1",
      environment: "test_dev",
      host: "10.0.0.10",
      provider: "local_vm",
      owner: "dev",
      expiration_state: "unknown",
      health: "ready",
    },
    {
      id: "prod-1",
      environment: "production",
      host: "prod.internal",
      provider: "cloud",
      owner: "ops",
      expires_at: "2026-09-30",
      expiration_state: "warning",
      maintenance_window: "due:2026-05-05",
      health: "approval_required",
    },
  ],
  lifecycle_alerts: [
    {
      id: "lifecycle-alert-prod-1-maintenance-due",
      resource_id: "prod-1",
      environment: "production",
      type: "maintenance_due",
      severity: "warning",
      status: "open",
      decision: "RESOURCE_MAINTENANCE_DUE",
      reason: "maintenance_window_due",
      expiration_state: "warning",
      expires_at: "2026-09-30",
      maintenance_window: "due:2026-05-05",
      health_status: "approval_required",
      created_at: "2026-05-05T00:47:00.000Z",
    },
  ],
  maintenance_records: [
    {
      id: "maintenance-prod-1-expiration-alert-20260505004600",
      resource_id: "prod-1",
      environment: "production",
      type: "expiration_alert",
      status: "open",
      decision: "MAINTENANCE_REQUIRED",
      expiration_state: "warning",
      expires_at: "2026-09-30",
      reason: "expiration_warning",
      created_at: "2026-05-05T00:46:00.000Z",
    },
  ],
  deployments: [
    {
      id: "deployment-v0-1-0-test-dev",
      release_id: "release-v0.1.0",
      environment: "test_dev",
      status: "planned",
      decision: "DEPLOY_PLAN_READY",
      reasons: ["release_and_resources_ready"],
      resource_count: 1,
      created_at: "2026-05-05T00:00:00.000Z",
    },
  ],
  executions: [
    {
      id: "deploy-exec-dry-run",
      deployment_id: "deployment-v0-1-0-test-dev",
      environment: "test_dev",
      mode: "dry_run",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
      reasons: ["no_remote_or_local_commands_executed"],
      step_count: 4,
      smoke_status: "skipped",
      monitor_status: "skipped",
      rollback_required: false,
      started_at: "2026-05-05T00:12:00.000Z",
    },
    {
      id: "deploy-exec-monitor-failed",
      deployment_id: "deployment-v0-1-0-test-dev",
      release_id: "release-v0.1.0",
      environment: "production",
      mode: "ssh_execute",
      status: "failed",
      decision: "DEPLOY_EXECUTION_MONITOR_FAILED",
      reasons: ["monitor_failed", "rollback_runbook_created"],
      step_count: 5,
      smoke_status: "passed",
      monitor_status: "failed",
      rollback_required: true,
      approval_id: "approval-deploy-production-ssh-execute",
      approval_consumed: true,
      started_at: "2026-05-05T00:14:00.000Z",
      finished_at: "2026-05-05T00:18:00.000Z",
    },
  ],
  post_deployment_histories: [
    {
      id: "post-deployment-history-deploy-exec-dry-run",
      execution_id: "deploy-exec-dry-run",
      deployment_id: "deployment-v0-1-0-test-dev",
      release_id: "release-v0.1.0",
      environment: "test_dev",
      status: "skipped",
      decision: "POST_DEPLOYMENT_NOT_APPLICABLE",
      failure_class: "none",
      severity: "",
      checks: [],
      rollback: {
        required: false,
        status: "not_applicable",
        decision: "",
        step_count: 0,
        actions: [],
      },
      evidence_ids: ["evidence-deploy-exec-dry-run"],
      artifacts: [{ kind: "deployment_execution", id: "deploy-exec-dry-run", path: ".moyuan/lifecycle/deployments/executions/deploy-exec-dry-run.json" }],
      reasons: ["no_remote_or_local_commands_executed"],
      created_at: "2026-05-05T00:12:02.000Z",
    },
  ],
  rollback_executions: [
    {
      id: "rollback-exec-deploy-exec-monitor-failed-preview",
      execution_id: "deploy-exec-monitor-failed",
      deployment_id: "deployment-v0-1-0-test-dev",
      release_id: "release-v0.1.0",
      environment: "production",
      mode: "preview",
      status: "completed",
      decision: "ROLLBACK_PREVIEW_READY",
      reasons: ["rollback_preview_only"],
      step_count: 2,
      approval_consumed: false,
      execution_enabled: false,
      started_at: "2026-05-05T00:18:20.000Z",
      finished_at: "2026-05-05T00:18:21.000Z",
    },
  ],
  monitor_summaries: [
    {
      id: "monitor-summary-production-demo",
      environment: "production",
      status: "critical",
      decision: "PRODUCTION_MONITOR_CRITICAL",
      reasons: ["history_count:1", "failed_count:1", "rollback_count:1"],
      window_size: 5,
      history_count: 1,
      failed_count: 1,
      blocked_count: 0,
      manual_count: 0,
      rollback_count: 1,
      failure_classes: { monitor_failed: 1 },
      latest: [
        {
          id: "post-deployment-history-deploy-exec-monitor-failed",
          execution_id: "deploy-exec-monitor-failed",
          deployment_id: "deployment-v0-1-0-test-dev",
          release_id: "release-v0.1.0",
          environment: "production",
          status: "failed",
          decision: "POST_DEPLOYMENT_FAILED",
          failure_class: "monitor_failed",
          severity: "critical",
          rollback: true,
          created_at: "2026-05-05T00:18:03.000Z",
        },
      ],
      evidence_ids: ["evidence-deploy-exec-dry-run"],
      created_at: "2026-05-05T00:18:30.000Z",
    },
  ],
  release_provider_executions: [
    {
      id: "release-provider-preview-v0-1-0",
      release_id: "release-v0.1.0",
      version: "v0.1.0",
      provider: "github",
      mode: "preview",
      status: "completed",
      decision: "RELEASE_PROVIDER_PREVIEW_READY",
      reasons: ["no_remote_release_actions_executed"],
      approval_consumed: false,
      write_enabled: false,
      action_count: 3,
      remote_status: "planned",
      started_at: "2026-05-05T00:10:00.000Z",
      finished_at: "2026-05-05T00:10:02.000Z",
    },
  ],
  evidence: [
    {
      id: "evidence-deploy-exec-dry-run",
      parent_type: "deployment_execution",
      parent_id: "deploy-exec-dry-run",
      subject_type: "deployment",
      subject_id: "deployment-v0-1-0-test-dev",
      operation: "deployment.execute.dry_run",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
      reasons: ["no_remote_or_local_commands_executed"],
      artifacts: [{ kind: "deployment_execution", id: "deploy-exec-dry-run", path: ".moyuan/lifecycle/deployments/executions/deploy-exec-dry-run.json" }],
      artifact_count: 1,
      created_at: "2026-05-05T00:12:02.000Z",
    },
    {
      id: "evidence-release-provider-preview",
      parent_type: "release_provider_execution",
      parent_id: "release-provider-preview-v0-1-0",
      subject_type: "release",
      subject_id: "release-v0.1.0",
      operation: "release.provider.preview",
      status: "completed",
      decision: "RELEASE_PROVIDER_PREVIEW_READY",
      reasons: ["no_remote_release_actions_executed"],
      artifacts: [
        {
          kind: "provider_execution",
          id: "release-provider-preview-v0-1-0",
          path: ".moyuan/lifecycle/releases/provider-executions/release-provider-preview-v0-1-0.json",
        },
      ],
      artifact_count: 1,
      created_at: "2026-05-05T00:10:02.000Z",
    },
  ],
  operation_history: [
    {
      id: "deploy-exec-dry-run",
      type: "deployment",
      title: "Deployment dry_run",
      detail: "DEPLOY_EXECUTION_DRY_RUN / 4 steps",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
      tone: "ok",
      time: "00:12",
      occurred_at: "2026-05-05T00:12:00.000Z",
      primary_ref: "deployment-v0-1-0-test-dev",
      secondary_ref: "test_dev",
      evidence_ids: ["evidence-deploy-exec-dry-run"],
      reasons: ["no_remote_or_local_commands_executed"],
      metadata: ["environment test_dev", "4 steps"],
    },
    {
      id: "release-provider-preview-v0-1-0",
      type: "release_provider",
      title: "Release provider preview",
      detail: "RELEASE_PROVIDER_PREVIEW_READY / 3 actions",
      status: "completed",
      decision: "RELEASE_PROVIDER_PREVIEW_READY",
      tone: "ok",
      time: "00:10",
      occurred_at: "2026-05-05T00:10:02.000Z",
      primary_ref: "release-v0.1.0",
      secondary_ref: "github",
      evidence_ids: ["evidence-release-provider-preview"],
      reasons: ["no_remote_release_actions_executed"],
      metadata: ["preview guarded", "approval not consumed", "remote planned"],
    },
  ],
  operation_details: [
    {
      id: "deploy-exec-dry-run",
      operation_type: "deployment",
      operation: "deployment.execute.dry_run",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
      reasons: ["no_remote_or_local_commands_executed"],
      primary_ref: "deployment-v0-1-0-test-dev",
      secondary_ref: "test_dev",
      started_at: "2026-05-05T00:12:00.000Z",
      finished_at: "2026-05-05T00:12:02.000Z",
      summary: {
        mode: "dry_run",
        deployment_id: "deployment-v0-1-0-test-dev",
        environment: "test_dev",
        step_count: 4,
        resource_count: 1,
        evidence_count: 1,
        artifact_count: 1,
      },
      evidence: [
        {
          id: "evidence-deploy-exec-dry-run",
          parent_type: "deployment_execution",
          parent_id: "deploy-exec-dry-run",
          subject_type: "deployment",
          subject_id: "deployment-v0-1-0-test-dev",
          operation: "deployment.execute.dry_run",
          status: "completed",
          decision: "DEPLOY_EXECUTION_DRY_RUN",
          reasons: ["no_remote_or_local_commands_executed"],
          artifacts: [{ kind: "deployment_execution", id: "deploy-exec-dry-run", path: ".moyuan/lifecycle/deployments/executions/deploy-exec-dry-run.json" }],
          artifact_count: 1,
          created_at: "2026-05-05T00:12:02.000Z",
        },
      ],
      artifacts: [{ kind: "deployment_execution", id: "deploy-exec-dry-run", path: ".moyuan/lifecycle/deployments/executions/deploy-exec-dry-run.json" }],
    },
    {
      id: "release-provider-preview-v0-1-0",
      operation_type: "release_provider",
      operation: "release.provider.preview",
      status: "completed",
      decision: "RELEASE_PROVIDER_PREVIEW_READY",
      reasons: ["no_remote_release_actions_executed"],
      primary_ref: "release-v0.1.0",
      secondary_ref: "github",
      started_at: "2026-05-05T00:10:00.000Z",
      finished_at: "2026-05-05T00:10:02.000Z",
      summary: {
        mode: "preview",
        release_id: "release-v0.1.0",
        version: "v0.1.0",
        provider: "github",
        action_count: 3,
        evidence_count: 1,
        artifact_count: 1,
        remote_status: "planned",
      },
      evidence: [
        {
          id: "evidence-release-provider-preview",
          parent_type: "release_provider_execution",
          parent_id: "release-provider-preview-v0-1-0",
          subject_type: "release",
          subject_id: "release-v0.1.0",
          operation: "release.provider.preview",
          status: "completed",
          decision: "RELEASE_PROVIDER_PREVIEW_READY",
          reasons: ["no_remote_release_actions_executed"],
          artifacts: [
            {
              kind: "provider_execution",
              id: "release-provider-preview-v0-1-0",
              path: ".moyuan/lifecycle/releases/provider-executions/release-provider-preview-v0-1-0.json",
            },
          ],
          artifact_count: 1,
          created_at: "2026-05-05T00:10:02.000Z",
        },
      ],
      artifacts: [
        {
          kind: "provider_execution",
          id: "release-provider-preview-v0-1-0",
          path: ".moyuan/lifecycle/releases/provider-executions/release-provider-preview-v0-1-0.json",
        },
      ],
    },
  ],
  runs: [
    {
      run_id: "run-frontend-console",
      issue_id: "frontend-console",
      status: "completed",
      subagent_id: "subagent-frontend-console",
      runtime_id: "claude_cli",
      runtime_status: "completed",
      quality_status: "passed",
      quality_report_id: "quality-frontend-console",
      updated_at: "2026-05-05T00:18:00.000Z",
    },
    {
      run_id: "run-quality-review",
      issue_id: "quality-review",
      status: "running",
      subagent_id: "subagent-quality-review",
      runtime_id: "codex_cli",
      runtime_status: "running",
      quality_status: "pending",
      quality_report_id: "quality-review-pending",
      recovery_id: "recovery-run-quality-review-codex-cli",
      updated_at: "2026-05-05T00:24:00.000Z",
    },
  ],
  subagents: [
    {
      id: "subagent-frontend-console",
      issue_id: "frontend-console",
      run_id: "run-frontend-console",
      status: "completed",
      role: "frontend",
      runtime_id: "claude_cli",
      provider_id: "minimax-m27-claude",
      model_id: "MiniMax-M2.7",
      skills: ["grill-me", "tdd"],
      memory_scope: ["project", "frontend"],
      read_scope: ["apps/console", "docs/frontend"],
      write_scope: ["apps/console"],
      output_contract: ["diff_summary", "test_evidence", "review_notes"],
      retry_policy: "quality_retry",
      retry_count: 0,
      max_retries: 2,
      output_converged: true,
      updated_at: "2026-05-05T00:18:00.000Z",
    },
    {
      id: "subagent-quality-review",
      issue_id: "quality-review",
      run_id: "run-quality-review",
      status: "dispatched",
      role: "quality_guard",
      runtime_id: "codex_cli",
      provider_id: "codex_cli",
      skills: ["diagnose"],
      memory_scope: ["project", "quality"],
      read_scope: ["apps/console", "internal/api"],
      write_scope: [],
      output_contract: ["blocking_findings", "merge_decision"],
      retry_policy: "review_retry",
      retry_count: 1,
      max_retries: 2,
      recovery_id: "recovery-run-quality-review-codex-cli",
      failure_category: "runtime_failed",
      output_converged: false,
      updated_at: "2026-05-05T00:24:00.000Z",
    },
  ],
  runtime_recoveries: [
    {
      id: "recovery-run-quality-review-codex-cli",
      run_id: "run-quality-review",
      subagent_id: "subagent-quality-review",
      issue_id: "quality-review",
      runtime_id: "codex_cli",
      provider_id: "codex_cli",
      status: "archived",
      failure_category: "runtime_failed",
      fallback_candidate: "claude_cli",
      fallback_reason: "runtime_failed",
      resume_hint: "Resume native session, inspect stderr, then retry with quality_guard contract.",
      prompt_path: ".moyuan/runtimes/sessions/session-run-quality-review/prompt.md",
      stderr_path: ".moyuan/runtimes/sessions/session-run-quality-review/stderr.log",
      diff_summary_path: ".moyuan/runs/run-quality-review/diff-summary.md",
      changed_files: ["apps/console/components/console-workbench.tsx"],
      risks: ["runtime_failed"],
      created_at: "2026-05-05T00:23:00.000Z",
      updated_at: "2026-05-05T00:24:00.000Z",
    },
  ],
  operation_repair_candidates: [
    {
      id: "operation-repair-candidate-deploy-exec-smoke",
      status: "review_required",
      decision: "REPAIR_CANDIDATE_CREATED",
      operation_type: "deployment",
      operation_id: "deploy-exec-smoke",
      operation: "deployment.execute.local_shell",
      operation_status: "failed",
      operation_decision: "DEPLOY_SMOKE_FAILED",
      failure_class: "smoke_failed",
      signal_type: "smoke_failure",
      signal_id: "signal-deploy-smoke",
      bug_candidate_id: "bug-deploy-smoke",
      repair_plan_id: "repair-plan-deploy-smoke",
      evidence_refs: ["evidence-deploy-smoke"],
      reasons: ["operation_smoke_failed"],
      review_required: true,
      reviewed_at: "",
      reviewed_by: "",
      review_decision: "",
      review_reason: "",
      issue_id: "",
      repair_attempt_id: "",
      created_at: "2026-05-05T00:28:00.000Z",
    },
  ],
  control_loop_runs: [
    {
      id: "control-loop-20260505004100",
      status: "completed",
      decision: "CONTROL_LOOP_COMPLETED_WITH_ATTENTION",
      trigger: "console_manual",
      requested_by: "console-owner",
      max_steps: 5,
      step_timeout_ms: 30000,
      steps: [
        {
          id: "control-loop-20260505004100-step-01",
          type: "resource_lifecycle_scan",
          status: "attention_required",
          decision: "RESOURCE_LIFECYCLE_ATTENTION_REQUIRED",
          summary: "1 resource lifecycle alert",
          reasons: ["maintenance_due:prod-1"],
          artifact_count: 1,
          evidence_count: 1,
          duration_ms: 24,
          started_at: "2026-05-05T00:41:00.000Z",
          finished_at: "2026-05-05T00:41:00.024Z",
        },
        {
          id: "control-loop-20260505004100-step-02",
          type: "provider_ops_refresh",
          status: "completed",
          decision: "PROVIDER_OPS_REFRESH_COMPLETED",
          summary: "2 provider updates, 0 provider skips",
          reasons: ["minimax-m27-claude:provider_degraded_or_budget_warning"],
          artifact_count: 1,
          evidence_count: 1,
          duration_ms: 19,
          started_at: "2026-05-05T00:41:00.025Z",
          finished_at: "2026-05-05T00:41:00.044Z",
        },
      ],
      reasons: ["maintenance_due:prod-1"],
      started_at: "2026-05-05T00:41:00.000Z",
      finished_at: "2026-05-05T00:41:00.045Z",
    },
  ],
  batch_plans: [
    {
      id: "batch-phase11-console-20260505010000",
      epic_id: "phase11-epic",
      mode: "dry_run",
      status: "planned",
      decision: "BATCH_PLAN_READY",
      max_parallel: 3,
      dispatch_count: 2,
      waiting_count: 1,
      blocked_count: 0,
      write_scope_conflict_count: 1,
      runtime_slots: 3,
      reasons: ["dispatch_ready"],
      item_count: 3,
      created_at: "2026-05-05T01:00:00.000Z",
    },
  ],
  batch_runs: [
    {
      id: "batch-run-phase11-console-20260505010200",
      batch_id: "batch-phase11-console-20260505010000",
      epic_id: "phase11-epic",
      mode: "local_shell",
      status: "completed",
      decision: "BATCH_RUN_COMPLETED",
      requested_by: "console-owner",
      max_issues: 2,
      parallelism: 2,
      item_count: 2,
      accepted_count: 1,
      blocked_count: 0,
      needs_rework_count: 1,
      reasons: ["isolated_worktree_serial_execution"],
      items: [
        {
          issue_id: "backend-api",
          status: "completed",
          decision: "BATCH_ITEM_ACCEPTED",
          runtime_id: "local_shell",
          worktree_id: "worktree-backend-api",
          branch: "moyuan/phase11/backend-api/worktree-backend-api",
          worker_slot: 1,
          run_id: "run-backend-api",
          subagent_id: "subagent-backend-api",
          quality_report_id: "quality-backend-api",
        },
        {
          issue_id: "frontend-console",
          status: "failed",
          decision: "BATCH_ITEM_NEEDS_REWORK",
          reason: "needs_rework",
          runtime_id: "local_shell",
          worktree_id: "worktree-frontend-console",
          branch: "moyuan/phase11/frontend-console/worktree-frontend-console",
          worker_slot: 2,
        },
      ],
      started_at: "2026-05-05T01:02:00.000Z",
      finished_at: "2026-05-05T01:03:00.000Z",
    },
  ],
  worktrees: [
    {
      id: "worktree-backend-api",
      epic_id: "phase11-epic",
      batch_id: "batch-phase11-console-20260505010000",
      issue_id: "backend-api",
      status: "ready",
      decision: "WORKTREE_READY",
      worktree_path: ".moyuan/worktrees/worktree-backend-api",
      branch: "moyuan/phase11/backend-api/worktree-backend-api",
      base_ref: "main",
      reasons: ["worktree_created"],
      created_at: "2026-05-05T01:01:00.000Z",
    },
  ],
  merge_queues: [
    {
      id: "merge-queue-phase11-console-20260505010400",
      batch_id: "batch-phase11-console-20260505010000",
      epic_id: "phase11-epic",
      batch_run_id: "batch-run-phase11-console-20260505010200",
      status: "needs_rework",
      decision: "MERGE_QUEUE_NEEDS_REWORK",
      ready_count: 1,
      needs_rework_count: 1,
      blocked_count: 0,
      reasons: ["items_need_rework"],
      items: [
        {
          issue_id: "backend-api",
          status: "ready_to_merge",
          decision: "MERGE_QUEUE_ITEM_READY",
          quality_report_id: "quality-backend-api",
          worktree_id: "worktree-backend-api",
          branch: "moyuan/phase11/backend-api/worktree-backend-api",
        },
        {
          issue_id: "frontend-console",
          status: "needs_rework",
          decision: "MERGE_QUEUE_ITEM_NEEDS_REWORK",
          reason: "merge_decision_needs_rework",
          worktree_id: "worktree-frontend-console",
        },
      ],
      created_at: "2026-05-05T01:04:00.000Z",
    },
  ],
  integration_previews: [
    {
      id: "integration-preview-phase12-console-20260505011000",
      merge_queue_id: "merge-queue-phase11-console-20260505010400",
      batch_id: "batch-phase11-console-20260505010000",
      epic_id: "phase12-epic",
      status: "ready",
      decision: "INTEGRATION_PREVIEW_READY",
      reasons: ["all_ready_items_merge_cleanly"],
      base_ref: "main",
      integration_branch: "moyuan/integration/merge-queue-phase11-console/20260505011000",
      ready_count: 3,
      conflict_count: 0,
      blocked_count: 0,
      item_count: 3,
      items: [
        {
          issue_id: "backend-api",
          status: "ready",
          decision: "INTEGRATION_ITEM_READY",
          reason: "merge_clean",
          branch: "moyuan/phase12/backend-api/worktree-backend-api",
          worktree_id: "worktree-backend-api",
          commit: "4f2a9c1",
          changed_files: ["internal/api/router.go"],
          conflicted_files: [],
          protected_files: [],
        },
      ],
      created_at: "2026-05-05T01:10:00.000Z",
    },
  ],
  integration_applies: [
    {
      id: "integration-apply-phase12-console-20260505011200",
      preview_id: "integration-preview-phase12-console-20260505011000",
      merge_queue_id: "merge-queue-phase11-console-20260505010400",
      batch_id: "batch-phase11-console-20260505010000",
      epic_id: "phase12-epic",
      mode: "apply",
      status: "applied",
      decision: "INTEGRATION_APPLY_COMPLETED",
      reasons: ["local_integration_branch_updated"],
      approved: true,
      requested_by: "console-owner",
      source_branch: "moyuan/integration/merge-queue-phase11-console/20260505011000",
      target_branch: "moyuan/integration/applied/merge-queue-phase11-console",
      write_enabled: true,
      action_count: 2,
      started_at: "2026-05-05T01:12:00.000Z",
      finished_at: "2026-05-05T01:12:05.000Z",
    },
  ],
  release_batches: [
    {
      id: "release-batch-v0-2-0-20260505011500",
      integration_apply_id: "integration-apply-phase12-console-20260505011200",
      integration_preview_id: "integration-preview-phase12-console-20260505011000",
      merge_queue_id: "merge-queue-phase11-console-20260505010400",
      batch_id: "batch-phase11-console-20260505010000",
      epic_id: "phase12-epic",
      status: "suggested",
      decision: "RELEASE_BATCH_SUGGESTED",
      version: "v0.2.0",
      release_branch: "release/v0.2.0",
      source_branch: "moyuan/integration/applied/merge-queue-phase11-console",
      ready_item_count: 3,
      min_items: 3,
      reasons: ["ready_item_threshold_met"],
      commands: ["git checkout -b release/v0.2.0 moyuan/integration/applied/merge-queue-phase11-console", "git push origin release/v0.2.0", "git tag v0.2.0"],
      requested_by: "console-owner",
      created_at: "2026-05-05T01:15:00.000Z",
    },
  ],
  release_candidates: [
    {
      id: "release-candidate-v0-2-0-20260505011600",
      release_batch_id: "release-batch-v0-2-0-20260505011500",
      integration_apply_id: "integration-apply-phase12-console-20260505011200",
      status: "ready",
      decision: "RELEASE_CANDIDATE_READY",
      version: "v0.2.0",
      release_branch: "release/v0.2.0",
      source_branch: "moyuan/integration/applied/merge-queue-phase11-console",
      provider: "github",
      remote_name: "origin",
      ready_item_count: 3,
      deployment_targets: ["test_dev"],
      reasons: ["release_batch_ready"],
      created_at: "2026-05-05T01:16:00.000Z",
    },
  ],
  release_candidate_applies: [
    {
      id: "release-candidate-apply-v0-2-0-20260505011700",
      candidate_id: "release-candidate-v0-2-0-20260505011600",
      release_batch_id: "release-batch-v0-2-0-20260505011500",
      mode: "apply",
      status: "applied",
      decision: "RELEASE_BRANCH_APPLY_COMPLETED",
      reasons: ["local_release_branch_updated"],
      release_branch: "release/v0.2.0",
      source_branch: "moyuan/integration/applied/merge-queue-phase11-console",
      write_enabled: true,
      action_count: 2,
      started_at: "2026-05-05T01:17:00.000Z",
      finished_at: "2026-05-05T01:17:05.000Z",
    },
  ],
  release_candidate_provider_previews: [
    {
      id: "release-candidate-provider-preview-v0-2-0-20260505011800",
      candidate_id: "release-candidate-v0-2-0-20260505011600",
      release_batch_id: "release-batch-v0-2-0-20260505011500",
      version: "v0.2.0",
      provider: "github",
      status: "completed",
      decision: "RELEASE_CANDIDATE_PROVIDER_PREVIEW_READY",
      reasons: ["no_remote_release_actions_executed"],
      remote_action_count: 5,
      pr_mr_type: "pull_request",
      pr_mr_decision: "PR_MR_PREVIEW_READY",
      pr_mr_head_branch: "release/v0.2.0",
      created_at: "2026-05-05T01:18:00.000Z",
    },
  ],
  deployment_feedback: [
    {
      id: "candidate-deployment-feedback-release-candidate-v0-2-0-20260505011600",
      candidate_id: "release-candidate-v0-2-0-20260505011600",
      status: "passed",
      decision: "CANDIDATE_DEPLOYMENT_HEALTHY",
      failure_class: "none",
      severity: "",
      latest_execution_id: "deploy-exec-candidate-v0-2-0",
      latest_deployment_id: "deployment-release-candidate-v0-2-0-test-dev",
      environment: "test_dev",
      history_count: 2,
      rollback_required: false,
      evidence_count: 4,
      reasons: ["smoke_and_monitor_not_failed"],
      created_at: "2026-05-05T01:24:00.000Z",
    },
  ],
  visual_assets: [
    {
      id: "visual-diagram-multi-agent-20260505003000",
      diagram_spec_id: "diagram-multi-agent-20260505003000",
      diagram_type: "multi_agent",
      title: "多 Agent Issue 编排流程图",
      status: "planned",
      provider_id: "gpt_image_2",
      model_id: "gpt-image-2",
      size: "3072x2048",
      prompt_path: ".moyuan/visuals/prompts/diagram-multi-agent-20260505003000.prompt.md",
      spec_path: ".moyuan/visuals/specs/diagram-multi-agent-20260505003000.json",
      route_reason: "image-diagram strategy matched visual architecture output",
      created_at: "2026-05-05T00:30:00.000Z",
      updated_at: "2026-05-05T00:30:00.000Z",
    },
  ],
  visual_render_executions: [
    {
      id: "visual-render-visual-diagram-multi-agent-20260505003000-dry-run",
      asset_id: "visual-diagram-multi-agent-20260505003000",
      diagram_spec_id: "diagram-multi-agent-20260505003000",
      diagram_type: "multi_agent",
      title: "多 Agent Issue 编排流程图",
      mode: "dry_run",
      status: "completed",
      decision: "VISUAL_RENDER_DRY_RUN",
      reasons: ["no_image_api_called"],
      provider_id: "gpt_image_2",
      model_id: "gpt-image-2",
      size: "3072x2048",
      prompt_path: ".moyuan/visuals/prompts/diagram-multi-agent-20260505003000.prompt.md",
      spec_path: ".moyuan/visuals/specs/diagram-multi-agent-20260505003000.json",
      script_path: "scripts/generate-multi-agent-flow-image.js",
      step_count: 1,
      started_at: "2026-05-05T00:34:00.000Z",
      finished_at: "2026-05-05T00:34:00.000Z",
    },
  ],
  quality_explanations: [
    {
      report_id: "quality-frontend-console",
      task_id: "frontend-console",
      status: "passed",
      review_status: "accepted",
      decision: "QUALITY_ACCEPTED",
      reasons: ["quality_and_review_accepted"],
      checks: [
        { type: "typecheck", status: "passed" },
        { type: "build", status: "passed" },
      ],
      findings: [],
    },
    {
      report_id: "quality-review-pending",
      task_id: "quality-review",
      status: "pending",
      review_status: "pending",
      decision: "QUALITY_PENDING",
      reasons: ["waiting_for_frontend_diff"],
      checks: [{ type: "review", status: "pending" }],
      findings: [
        {
          id: "finding-waiting-diff",
          severity: "medium",
          category: "review_waiting",
          message: "Quality guard waits for frontend diff and test evidence before merge decision.",
          blocking: true,
        },
      ],
    },
  ],
  audit_events: [
    {
      id: "audit-001",
      channel: "audit",
      stream: "audit",
      event: "provider.ops.refreshed",
      ts: "2026-05-05T00:36:00.000Z",
      status: "degraded",
      decision: "probe_secret_ref_not_resolved",
      reason: "provider probe stayed controlled and did not read secret refs",
    },
    {
      id: "audit-002",
      channel: "release",
      stream: "release",
      event: "deployment.execution.created",
      ts: "2026-05-05T00:34:00.000Z",
      run_id: "deploy-exec-dry-run",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
    },
    {
      id: "audit-003",
      channel: "run",
      stream: "run",
      event: "runtime.recovery.archived",
      ts: "2026-05-05T00:24:00.000Z",
      issue_id: "quality-review",
      run_id: "run-quality-review",
      status: "archived",
      reason: "runtime_failed",
    },
  ],
  approvals: [
    {
      id: "approval-deploy-production",
      target_type: "deployment",
      target_id: "deployment-v0-1-0-production",
      action: "deploy.production",
      risk_level: "critical",
      status: "pending",
      decision: "APPROVAL_PENDING",
      requested_by: "system",
      request_reason: "production deployment requires approval, smoke and rollback plan",
      requested_at: "2026-05-05T00:38:00.000Z",
    },
    {
      id: "approval-visual-script",
      target_type: "visual_render",
      target_id: "visual-render-visual-diagram-multi-agent-20260505003000-script",
      action: "visual.render.script",
      risk_level: "high",
      status: "approved",
      decision: "APPROVAL_APPROVED",
      requested_by: "visualization_owner",
      request_reason: "script render needs controlled image API credential injection",
      decided_by: "owner",
      decision_reason: "diagram spec and auth refs reviewed",
      requested_at: "2026-05-05T00:32:00.000Z",
      decided_at: "2026-05-05T00:33:00.000Z",
    },
  ],
  git_provider_plans: [
    {
      id: "git-provider-plan-frontend-console-20260505004300",
      issue_id: "frontend-console",
      candidate_id: "",
      status: "pr_mr_plan_ready",
      decision: "PR_MR_ALLOWED",
      provider: "github",
      remote_name: "origin",
      base_branch: "main",
      target_branch: "feature/frontend-console",
      pr_mr_type: "pull_request",
      create_mode: "manual",
      remote_link: "https://github.com/tiammomo/moyuan-code/compare/main...feature%2Ffrontend-console?expand=1",
      remote_status: "manual_required",
      sync_decision: "PR_MR_STATUS_MANUAL_REQUIRED",
      sync_reason: "manual_create_mode_or_provider_without_pr_mr_api",
      manual_required: true,
      created_at: "2026-05-05T00:43:00.000Z",
    },
  ],
  auth_sessions: [
    {
      id: "session-owner-20260505004000",
      user_id: "owner",
      display_name: "Project Owner",
      roles: ["project_owner", "approver"],
      status: "active",
      created_at: "2026-05-05T00:40:00.000Z",
    },
    {
      id: "session-reviewer-20260505003600",
      user_id: "reviewer",
      display_name: "Quality Reviewer",
      roles: ["reviewer"],
      status: "active",
      created_at: "2026-05-05T00:36:00.000Z",
    },
  ],
  api_tokens: [
    {
      id: "api-token-ci-dry-run-20260505003900",
      name: "CI Dry Run",
      actor_id: "svc-ci",
      scopes: ["project:read", "deploy:dry-run"],
      token_prefix: "moyuan_demo_pref",
      status: "active",
      created_at: "2026-05-05T00:39:00.000Z",
    },
  ],
  service_accounts: [
    {
      id: "svc-release-bot",
      name: "Release Bot",
      roles: ["release_bot", "deploy_executor"],
      status: "active",
      created_at: "2026-05-05T00:38:00.000Z",
    },
  ],
  timeline: [
    {
      id: "t1",
      title: "Project comprehension",
      detail: "profile, module map, commands, memory candidates",
      tone: "ok",
      time: "09:10",
    },
    {
      id: "t2",
      title: "Provider route",
      detail: "frontend -> claude_cli -> minimax-m27-claude",
      tone: "running",
      time: "09:26",
    },
    {
      id: "t3",
      title: "Quality gate",
      detail: "waiting for frontend diff and test evidence",
      tone: "warning",
      time: "09:37",
    },
  ],
  quality: [
    {
      id: "q1",
      title: "Protected paths",
      detail: ".env and policy paths are blocked",
      status: "enforced",
      severity: "ok",
    },
    {
      id: "q2",
      title: "Test coverage",
      detail: "frontend smoke and API adapter tests required",
      status: "pending",
      severity: "warning",
    },
    {
      id: "q3",
      title: "Runtime diff",
      detail: "changed files captured before review",
      status: "enabled",
      severity: "ok",
    },
  ],
  memory: [
    { id: "m1", kind: "decision", summary: "Web Console uses Next.js 16 on port 3000.", score: 0.96 },
    { id: "m2", kind: "pattern", summary: "Frontend issues prefer claude_cli with MiniMax-M2.7 profile.", score: 0.91 },
    { id: "m3", kind: "risk", summary: "High-risk deployment requires approval and audit trail.", score: 0.88 },
  ],
};
