import type { ConsoleSnapshot } from "./types";

export const demoSnapshot: ConsoleSnapshot = {
  mode: "demo",
  backendStatus: "warning",
  generatedAt: "2026-05-05T00:00:00.000Z",
  project: {
    id: "moyuan-code",
    name: "moyuan-code",
    root: "/home/tiammomo/projects/dev/moyuan-code",
    status: "planning-ready",
    source: { provider: "github", url: "git@github.com:tiammomo/moyuan-code.git" },
  },
  stats: {
    issues: 7,
    accepted: 4,
    blocked: 1,
    providers: 5,
    resources: 2,
    deployments: 1,
    executions: 1,
    runs: 2,
    recoveries: 1,
    visual_assets: 1,
    visual_render_executions: 1,
  },
  issues: [
    {
      id: "req-clarify",
      title: "需求澄清与 Issue Graph",
      role: "requirement_refiner",
      status: "accepted",
      runtime: "claude_cli",
      provider: "claude_cli",
      quality: "accepted",
      lane: "plan",
    },
    {
      id: "api-contract",
      title: "控制面 API 契约",
      role: "architect",
      status: "accepted",
      depends_on: ["req-clarify"],
      runtime: "claude_cli",
      provider: "claude_cli",
      quality: "accepted",
      lane: "plan",
    },
    {
      id: "backend-state-api",
      title: "Gin/GORM 状态 API",
      role: "backend",
      status: "accepted",
      depends_on: ["api-contract"],
      runtime: "codex_cli",
      provider: "codex_cli",
      quality: "passed",
      lane: "backend",
    },
    {
      id: "frontend-console",
      title: "Next.js 16 Console",
      role: "frontend",
      status: "running",
      depends_on: ["api-contract"],
      run_id: "run-frontend-console",
      subagent_id: "subagent-frontend-console",
      runtime: "claude_cli",
      runtime_status: "completed",
      provider: "minimax-m27-claude",
      quality: "passed",
      quality_report_id: "quality-frontend-console",
      quality_decision: "QUALITY_ACCEPTED",
      quality_reasons: ["quality_and_review_accepted"],
      review_status: "accepted",
      skills: ["grill-me", "tdd"],
      output_contract: ["diff_summary", "test_evidence", "review_notes"],
      lane: "frontend",
    },
    {
      id: "quality-review",
      title: "Diff-first Review",
      role: "quality_guard",
      status: "waiting",
      depends_on: ["backend-state-api", "frontend-console"],
      run_id: "run-quality-review",
      subagent_id: "subagent-quality-review",
      runtime: "codex_cli",
      runtime_status: "running",
      provider: "codex_cli",
      quality: "pending",
      quality_report_id: "quality-review-pending",
      quality_decision: "QUALITY_PENDING",
      quality_reasons: ["waiting_for_frontend_diff"],
      review_status: "pending",
      blocked_reason: "waiting_frontend_decision",
      skills: ["diagnose"],
      output_contract: ["blocking_findings", "merge_decision"],
      lane: "quality",
    },
    {
      id: "release-suggest",
      title: "Release Suggestion",
      role: "release_manager",
      status: "ready",
      depends_on: ["quality-review"],
      runtime: "codex_cli",
      provider: "codex_cli",
      lane: "release",
    },
    {
      id: "deploy-plan",
      title: "Deploy / Smoke / Monitor",
      role: "devops",
      status: "blocked",
      depends_on: ["release-suggest"],
      blocked_reason: "production_approval_required",
      lane: "release",
    },
  ],
  schedule: [
    { issue_id: "frontend-console", status: "dispatch", runtime_id: "claude_cli" },
    { issue_id: "quality-review", status: "waiting", runtime_id: "codex_cli", blocked_reason: "waiting_frontend_decision" },
    { issue_id: "deploy-plan", status: "blocked", runtime_id: "codex_cli", blocked_reason: "production_approval_required" },
  ],
  subagent_backlog: [
    {
      issue_id: "quality-review",
      subagent_id: "subagent-quality-review",
      status: "retrying",
      reason: "runtime_failed",
      recovery_id: "recovery-run-quality-review-codex-cli",
      failure_category: "runtime_failed",
      retry_count: 1,
      max_retries: 2,
    },
  ],
  providers: [
    {
      id: "minimax-m27-claude",
      name: "MiniMax M2.7 via Claude CLI",
      vendor: "minimax",
      api_type: "anthropic-compatible",
      enabled: true,
      runtime_id: "claude_cli",
      model: "MiniMax-M2.7",
      use_cases: ["frontend", "planning", "review"],
    },
    {
      id: "codex_cli",
      name: "Codex CLI",
      vendor: "openai",
      api_type: "codex_cli",
      enabled: true,
      runtime_id: "codex_cli",
      use_cases: ["backend", "testing", "review", "repair"],
    },
    {
      id: "gpt_image_2",
      name: "GPT Image 2",
      vendor: "openai",
      api_type: "image",
      enabled: false,
      model: "gpt-image-2",
      use_cases: ["architecture_diagram"],
    },
  ],
  resources: [
    {
      id: "dev-1",
      environment: "test_dev",
      host: "10.0.0.10",
      provider: "local_vm",
      owner: "dev",
      health: "ready",
    },
    {
      id: "prod-1",
      environment: "production",
      host: "prod.internal",
      provider: "cloud",
      owner: "ops",
      expires_at: "2026-09-30",
      health: "approval_required",
    },
  ],
  deployments: [
    {
      id: "deployment-v0-1-0-test-dev",
      release_id: "release-v0.1.0",
      environment: "test_dev",
      status: "planned",
      decision: "DEPLOY_PLAN_READY",
      reasons: ["release_and_resources_ready"],
      resource_count: 1,
      created_at: "2026-05-05T00:00:00.000Z",
    },
  ],
  executions: [
    {
      id: "deploy-exec-dry-run",
      deployment_id: "deployment-v0-1-0-test-dev",
      environment: "test_dev",
      mode: "dry_run",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
      reasons: ["no_remote_or_local_commands_executed"],
      step_count: 4,
      started_at: "2026-05-05T00:12:00.000Z",
    },
  ],
  runs: [
    {
      run_id: "run-frontend-console",
      issue_id: "frontend-console",
      status: "completed",
      subagent_id: "subagent-frontend-console",
      runtime_id: "claude_cli",
      runtime_status: "completed",
      quality_status: "passed",
      quality_report_id: "quality-frontend-console",
      updated_at: "2026-05-05T00:18:00.000Z",
    },
    {
      run_id: "run-quality-review",
      issue_id: "quality-review",
      status: "running",
      subagent_id: "subagent-quality-review",
      runtime_id: "codex_cli",
      runtime_status: "running",
      quality_status: "pending",
      quality_report_id: "quality-review-pending",
      recovery_id: "recovery-run-quality-review-codex-cli",
      updated_at: "2026-05-05T00:24:00.000Z",
    },
  ],
  subagents: [
    {
      id: "subagent-frontend-console",
      issue_id: "frontend-console",
      run_id: "run-frontend-console",
      status: "completed",
      role: "frontend",
      runtime_id: "claude_cli",
      provider_id: "minimax-m27-claude",
      model_id: "MiniMax-M2.7",
      skills: ["grill-me", "tdd"],
      memory_scope: ["project", "frontend"],
      read_scope: ["apps/console", "docs/frontend"],
      write_scope: ["apps/console"],
      output_contract: ["diff_summary", "test_evidence", "review_notes"],
      retry_policy: "quality_retry",
      retry_count: 0,
      max_retries: 2,
      output_converged: true,
      updated_at: "2026-05-05T00:18:00.000Z",
    },
    {
      id: "subagent-quality-review",
      issue_id: "quality-review",
      run_id: "run-quality-review",
      status: "dispatched",
      role: "quality_guard",
      runtime_id: "codex_cli",
      provider_id: "codex_cli",
      skills: ["diagnose"],
      memory_scope: ["project", "quality"],
      read_scope: ["apps/console", "internal/api"],
      write_scope: [],
      output_contract: ["blocking_findings", "merge_decision"],
      retry_policy: "review_retry",
      retry_count: 1,
      max_retries: 2,
      recovery_id: "recovery-run-quality-review-codex-cli",
      failure_category: "runtime_failed",
      output_converged: false,
      updated_at: "2026-05-05T00:24:00.000Z",
    },
  ],
  runtime_recoveries: [
    {
      id: "recovery-run-quality-review-codex-cli",
      run_id: "run-quality-review",
      subagent_id: "subagent-quality-review",
      issue_id: "quality-review",
      runtime_id: "codex_cli",
      provider_id: "codex_cli",
      status: "archived",
      failure_category: "runtime_failed",
      fallback_candidate: "claude_cli",
      fallback_reason: "runtime_failed",
      resume_hint: "Resume native session, inspect stderr, then retry with quality_guard contract.",
      prompt_path: ".moyuan/runtimes/sessions/session-run-quality-review/prompt.md",
      stderr_path: ".moyuan/runtimes/sessions/session-run-quality-review/stderr.log",
      diff_summary_path: ".moyuan/runs/run-quality-review/diff-summary.md",
      changed_files: ["apps/console/components/console-workbench.tsx"],
      risks: ["runtime_failed"],
      created_at: "2026-05-05T00:23:00.000Z",
      updated_at: "2026-05-05T00:24:00.000Z",
    },
  ],
  visual_assets: [
    {
      id: "visual-diagram-multi-agent-20260505003000",
      diagram_spec_id: "diagram-multi-agent-20260505003000",
      diagram_type: "multi_agent",
      title: "多 Agent Issue 编排流程图",
      status: "planned",
      provider_id: "gpt_image_2",
      model_id: "gpt-image-2",
      size: "3072x2048",
      prompt_path: ".moyuan/visuals/prompts/diagram-multi-agent-20260505003000.prompt.md",
      spec_path: ".moyuan/visuals/specs/diagram-multi-agent-20260505003000.json",
      route_reason: "image-diagram strategy matched visual architecture output",
      created_at: "2026-05-05T00:30:00.000Z",
      updated_at: "2026-05-05T00:30:00.000Z",
    },
  ],
  visual_render_executions: [
    {
      id: "visual-render-visual-diagram-multi-agent-20260505003000-dry-run",
      asset_id: "visual-diagram-multi-agent-20260505003000",
      diagram_spec_id: "diagram-multi-agent-20260505003000",
      diagram_type: "multi_agent",
      title: "多 Agent Issue 编排流程图",
      mode: "dry_run",
      status: "completed",
      decision: "VISUAL_RENDER_DRY_RUN",
      reasons: ["no_image_api_called"],
      provider_id: "gpt_image_2",
      model_id: "gpt-image-2",
      size: "3072x2048",
      prompt_path: ".moyuan/visuals/prompts/diagram-multi-agent-20260505003000.prompt.md",
      spec_path: ".moyuan/visuals/specs/diagram-multi-agent-20260505003000.json",
      script_path: "scripts/generate-multi-agent-flow-image.js",
      step_count: 1,
      started_at: "2026-05-05T00:34:00.000Z",
      finished_at: "2026-05-05T00:34:00.000Z",
    },
  ],
  quality_explanations: [
    {
      report_id: "quality-frontend-console",
      task_id: "frontend-console",
      status: "passed",
      review_status: "accepted",
      decision: "QUALITY_ACCEPTED",
      reasons: ["quality_and_review_accepted"],
      checks: [
        { type: "typecheck", status: "passed" },
        { type: "build", status: "passed" },
      ],
      findings: [],
    },
    {
      report_id: "quality-review-pending",
      task_id: "quality-review",
      status: "pending",
      review_status: "pending",
      decision: "QUALITY_PENDING",
      reasons: ["waiting_for_frontend_diff"],
      checks: [{ type: "review", status: "pending" }],
      findings: [
        {
          id: "finding-waiting-diff",
          severity: "medium",
          category: "review_waiting",
          message: "Quality guard waits for frontend diff and test evidence before merge decision.",
          blocking: true,
        },
      ],
    },
  ],
  audit_events: [
    {
      id: "audit-001",
      channel: "audit",
      stream: "audit",
      event: "provider.ops.refreshed",
      ts: "2026-05-05T00:36:00.000Z",
      status: "degraded",
      decision: "probe_secret_ref_not_resolved",
      reason: "provider probe stayed controlled and did not read secret refs",
    },
    {
      id: "audit-002",
      channel: "release",
      stream: "release",
      event: "deployment.execution.created",
      ts: "2026-05-05T00:34:00.000Z",
      run_id: "deploy-exec-dry-run",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
    },
    {
      id: "audit-003",
      channel: "run",
      stream: "run",
      event: "runtime.recovery.archived",
      ts: "2026-05-05T00:24:00.000Z",
      issue_id: "quality-review",
      run_id: "run-quality-review",
      status: "archived",
      reason: "runtime_failed",
    },
  ],
  approvals: [
    {
      id: "approval-deploy-production",
      target_type: "deployment",
      target_id: "deployment-v0-1-0-production",
      action: "deploy.production",
      risk_level: "critical",
      status: "pending",
      decision: "APPROVAL_PENDING",
      requested_by: "system",
      request_reason: "production deployment requires approval, smoke and rollback plan",
      requested_at: "2026-05-05T00:38:00.000Z",
    },
    {
      id: "approval-visual-script",
      target_type: "visual_render",
      target_id: "visual-render-visual-diagram-multi-agent-20260505003000-script",
      action: "visual.render.script",
      risk_level: "high",
      status: "approved",
      decision: "APPROVAL_APPROVED",
      requested_by: "visualization_owner",
      request_reason: "script render needs controlled image API credential injection",
      decided_by: "owner",
      decision_reason: "diagram spec and auth refs reviewed",
      requested_at: "2026-05-05T00:32:00.000Z",
      decided_at: "2026-05-05T00:33:00.000Z",
    },
  ],
  timeline: [
    {
      id: "t1",
      title: "Project comprehension",
      detail: "profile, module map, commands, memory candidates",
      tone: "ok",
      time: "09:10",
    },
    {
      id: "t2",
      title: "Provider route",
      detail: "frontend -> claude_cli -> minimax-m27-claude",
      tone: "running",
      time: "09:26",
    },
    {
      id: "t3",
      title: "Quality gate",
      detail: "waiting for frontend diff and test evidence",
      tone: "warning",
      time: "09:37",
    },
  ],
  quality: [
    {
      id: "q1",
      title: "Protected paths",
      detail: ".env and policy paths are blocked",
      status: "enforced",
      severity: "ok",
    },
    {
      id: "q2",
      title: "Test coverage",
      detail: "frontend smoke and API adapter tests required",
      status: "pending",
      severity: "warning",
    },
    {
      id: "q3",
      title: "Runtime diff",
      detail: "changed files captured before review",
      status: "enabled",
      severity: "ok",
    },
  ],
  memory: [
    { id: "m1", kind: "decision", summary: "Web Console uses Next.js 16 on port 3000.", score: 0.96 },
    { id: "m2", kind: "pattern", summary: "Frontend issues prefer claude_cli with MiniMax-M2.7 profile.", score: 0.91 },
    { id: "m3", kind: "risk", summary: "High-risk deployment requires approval and audit trail.", score: 0.88 },
  ],
};
