import type { ConsoleSnapshot } from "./types";

export const demoSnapshot: ConsoleSnapshot = {
  mode: "demo",
  backendStatus: "warning",
  generatedAt: "2026-05-05T00:00:00.000Z",
  project: {
    id: "moyuan-code",
    name: "moyuan-code",
    root: "/home/tiammomo/projects/dev/moyuan-code",
    status: "planning-ready",
    source: { provider: "github", url: "git@github.com:tiammomo/moyuan-code.git" },
  },
  stats: {
    issues: 7,
    accepted: 4,
    blocked: 1,
    providers: 5,
    resources: 2,
    deployments: 1,
    executions: 1,
  },
  issues: [
    {
      id: "req-clarify",
      title: "需求澄清与 Issue Graph",
      role: "requirement_refiner",
      status: "accepted",
      runtime: "claude_cli",
      provider: "claude_cli",
      quality: "accepted",
      lane: "plan",
    },
    {
      id: "api-contract",
      title: "控制面 API 契约",
      role: "architect",
      status: "accepted",
      depends_on: ["req-clarify"],
      runtime: "claude_cli",
      provider: "claude_cli",
      quality: "accepted",
      lane: "plan",
    },
    {
      id: "backend-state-api",
      title: "Gin/GORM 状态 API",
      role: "backend",
      status: "accepted",
      depends_on: ["api-contract"],
      runtime: "codex_cli",
      provider: "codex_cli",
      quality: "passed",
      lane: "backend",
    },
    {
      id: "frontend-console",
      title: "Next.js 16 Console",
      role: "frontend",
      status: "running",
      depends_on: ["api-contract"],
      runtime: "claude_cli",
      provider: "minimax-m27-claude",
      quality: "pending",
      lane: "frontend",
    },
    {
      id: "quality-review",
      title: "Diff-first Review",
      role: "quality_guard",
      status: "waiting",
      depends_on: ["backend-state-api", "frontend-console"],
      runtime: "codex_cli",
      provider: "codex_cli",
      blocked_reason: "waiting_frontend_decision",
      lane: "quality",
    },
    {
      id: "release-suggest",
      title: "Release Suggestion",
      role: "release_manager",
      status: "ready",
      depends_on: ["quality-review"],
      runtime: "codex_cli",
      provider: "codex_cli",
      lane: "release",
    },
    {
      id: "deploy-plan",
      title: "Deploy / Smoke / Monitor",
      role: "devops",
      status: "blocked",
      depends_on: ["release-suggest"],
      blocked_reason: "production_approval_required",
      lane: "release",
    },
  ],
  schedule: [
    { issue_id: "frontend-console", status: "dispatch", runtime_id: "claude_cli" },
    { issue_id: "quality-review", status: "waiting", runtime_id: "codex_cli", blocked_reason: "waiting_frontend_decision" },
    { issue_id: "deploy-plan", status: "blocked", runtime_id: "codex_cli", blocked_reason: "production_approval_required" },
  ],
  providers: [
    {
      id: "minimax-m27-claude",
      name: "MiniMax M2.7 via Claude CLI",
      vendor: "minimax",
      api_type: "anthropic-compatible",
      enabled: true,
      runtime_id: "claude_cli",
      model: "MiniMax-M2.7",
      use_cases: ["frontend", "planning", "review"],
    },
    {
      id: "codex_cli",
      name: "Codex CLI",
      vendor: "openai",
      api_type: "codex_cli",
      enabled: true,
      runtime_id: "codex_cli",
      use_cases: ["backend", "testing", "review", "repair"],
    },
    {
      id: "gpt_image_2",
      name: "GPT Image 2",
      vendor: "openai",
      api_type: "image",
      enabled: false,
      model: "gpt-image-2",
      use_cases: ["architecture_diagram"],
    },
  ],
  resources: [
    {
      id: "dev-1",
      environment: "test_dev",
      host: "10.0.0.10",
      provider: "local_vm",
      owner: "dev",
      health: "ready",
    },
    {
      id: "prod-1",
      environment: "production",
      host: "prod.internal",
      provider: "cloud",
      owner: "ops",
      expires_at: "2026-09-30",
      health: "approval_required",
    },
  ],
  deployments: [
    {
      id: "deployment-v0-1-0-test-dev",
      release_id: "release-v0.1.0",
      environment: "test_dev",
      status: "planned",
      decision: "DEPLOY_PLAN_READY",
      reasons: ["release_and_resources_ready"],
      resource_count: 1,
      created_at: "2026-05-05T00:00:00.000Z",
    },
  ],
  executions: [
    {
      id: "deploy-exec-dry-run",
      deployment_id: "deployment-v0-1-0-test-dev",
      environment: "test_dev",
      mode: "dry_run",
      status: "completed",
      decision: "DEPLOY_EXECUTION_DRY_RUN",
      reasons: ["no_remote_or_local_commands_executed"],
      step_count: 4,
      started_at: "2026-05-05T00:12:00.000Z",
    },
  ],
  timeline: [
    {
      id: "t1",
      title: "Project comprehension",
      detail: "profile, module map, commands, memory candidates",
      tone: "ok",
      time: "09:10",
    },
    {
      id: "t2",
      title: "Provider route",
      detail: "frontend -> claude_cli -> minimax-m27-claude",
      tone: "running",
      time: "09:26",
    },
    {
      id: "t3",
      title: "Quality gate",
      detail: "waiting for frontend diff and test evidence",
      tone: "warning",
      time: "09:37",
    },
  ],
  quality: [
    {
      id: "q1",
      title: "Protected paths",
      detail: ".env and policy paths are blocked",
      status: "enforced",
      severity: "ok",
    },
    {
      id: "q2",
      title: "Test coverage",
      detail: "frontend smoke and API adapter tests required",
      status: "pending",
      severity: "warning",
    },
    {
      id: "q3",
      title: "Runtime diff",
      detail: "changed files captured before review",
      status: "enabled",
      severity: "ok",
    },
  ],
  memory: [
    { id: "m1", kind: "decision", summary: "Web Console uses Next.js 16 on port 3000.", score: 0.96 },
    { id: "m2", kind: "pattern", summary: "Frontend issues prefer claude_cli with MiniMax-M2.7 profile.", score: 0.91 },
    { id: "m3", kind: "risk", summary: "High-risk deployment requires approval and audit trail.", score: 0.88 },
  ],
};
