import path from 'node:path';
import { readdir } from 'node:fs/promises';
import { appendJsonl, fileExists, readJson, readYaml, writeText } from '../lib/fs.js';
import { getWorkspacePaths } from './paths.js';
import { logEvent } from './logging.js';
import { slugify } from '../lib/text.js';
import { updateWorkspaceProject } from './workspace.js';

async function safeReadJson(filePath) {
  try {
    return await readJson(filePath, null);
  } catch {
    return null;
  }
}

async function detectTopLevelEntries(rootDir) {
  try {
    const entries = await readdir(rootDir, { withFileTypes: true });
    return entries
      .filter((entry) => !entry.name.startsWith('.'))
      .map((entry) => ({
        name: entry.name,
        type: entry.isDirectory() ? 'directory' : 'file'
      }))
      .sort((a, b) => a.name.localeCompare(b.name));
  } catch {
    return [];
  }
}

async function detectStack(rootDir) {
  const stack = {
    languages: [],
    frameworks: [],
    package_managers: [],
    build_commands: [],
    test_commands: [],
    lint_commands: []
  };

  if (await fileExists(path.join(rootDir, 'package.json'))) {
    stack.languages.push('TypeScript/JavaScript');
    stack.package_managers.push('npm');
    const pkg = await safeReadJson(path.join(rootDir, 'package.json'));
    if (pkg?.scripts) {
      if (pkg.scripts.build) stack.build_commands = [`npm run build`];
      if (pkg.scripts.test) stack.test_commands = [`npm test`];
      if (pkg.scripts.lint) stack.lint_commands = [`npm run lint`];
    }
  }

  if (await fileExists(path.join(rootDir, 'pyproject.toml'))) {
    stack.languages.push('Python');
    stack.package_managers.push('pip/poetry');
  }

  if (await fileExists(path.join(rootDir, 'Cargo.toml'))) {
    stack.languages.push('Rust');
    stack.package_managers.push('cargo');
    stack.build_commands.push('cargo build');
    stack.test_commands.push('cargo test');
  }

  if (await fileExists(path.join(rootDir, 'go.mod'))) {
    stack.languages.push('Go');
    stack.package_managers.push('go');
    stack.build_commands.push('go build ./...');
    stack.test_commands.push('go test ./...');
  }

  if (stack.languages.length === 0) {
    stack.languages.push('unknown');
  }

  return stack;
}

async function detectRiskFiles(rootDir) {
  const riskFiles = [];
  for (const candidate of ['.env', '.env.local', '.env.production']) {
    if (await fileExists(path.join(rootDir, candidate))) {
      riskFiles.push(candidate);
    }
  }
  if (await fileExists(path.join(rootDir, 'package-lock.json'))) {
    riskFiles.push('package-lock.json');
  }
  if (await fileExists(path.join(rootDir, 'pnpm-lock.yaml'))) {
    riskFiles.push('pnpm-lock.yaml');
  }
  return riskFiles;
}

async function writeMarkdown(filePath, title, lines) {
  const content = [`# ${title}`, '', ...lines, ''].join('\n');
  await writeText(filePath, content);
}

export async function fullComprehension(rootDir, { since = null } = {}) {
  const paths = getWorkspacePaths(rootDir);
  const projectFile = await readYaml(paths.projectYaml, null);
  const repositoryFile = await readYaml(paths.repositoryYaml, null);
  const topEntries = await detectTopLevelEntries(rootDir);
  const stack = await detectStack(rootDir);
  const riskFiles = await detectRiskFiles(rootDir);
  const name = projectFile?.project?.name ?? path.basename(rootDir);
  const projectId = projectFile?.project?.id ?? slugify(name);

  const profile = {
    project_id: projectId,
    project_name: name,
    root: path.resolve(rootDir),
    detected_at: new Date().toISOString(),
    mode: since ? 'incremental' : 'full',
    since,
    stack,
    repository: repositoryFile?.repository ?? null,
    top_level_entries: topEntries,
    risk_files: riskFiles,
    summary: `${name} project comprehension generated by Phase 1 skeleton`
  };

  await writeMarkdown(path.join(paths.comprehensionDir, 'project-profile.md'), 'Project Profile', [
    `- Project ID: \`${profile.project_id}\``,
    `- Project Name: \`${profile.project_name}\``,
    `- Root: \`${profile.root}\``,
    `- Mode: \`${profile.mode}\``,
    `- Languages: ${stack.languages.join(', ')}`,
    `- Package Managers: ${stack.package_managers.join(', ') || 'none'}`,
    `- Build Commands: ${stack.build_commands.join(', ') || 'none'}`,
    `- Test Commands: ${stack.test_commands.join(', ') || 'none'}`,
    `- Lint Commands: ${stack.lint_commands.join(', ') || 'none'}`,
    `- Risk Files: ${riskFiles.length ? riskFiles.join(', ') : 'none'}`
  ]);

  await writeMarkdown(path.join(paths.comprehensionDir, 'module-map.md'), 'Module Map', [
    '## Top-Level Entries',
    ...topEntries.map((entry) => `- ${entry.type}: \`${entry.name}\``),
    '',
    '## Heuristic Responsibilities',
    '- `docs/` and `README` indicate design and documentation surfaces.',
    '- `scripts/` indicates automation and helper entry points.',
    '- `src/` indicates executable code or framework implementation.'
  ]);

  await writeMarkdown(path.join(paths.comprehensionDir, 'commands.md'), 'Commands', [
    '## Build',
    ...(stack.build_commands.length ? stack.build_commands.map((cmd) => `- ${cmd}`) : ['- none detected']),
    '',
    '## Test',
    ...(stack.test_commands.length ? stack.test_commands.map((cmd) => `- ${cmd}`) : ['- none detected']),
    '',
    '## Lint',
    ...(stack.lint_commands.length ? stack.lint_commands.map((cmd) => `- ${cmd}`) : ['- none detected'])
  ]);

  await writeMarkdown(path.join(paths.comprehensionDir, 'risk-files.md'), 'Risk Files', [
    ...(riskFiles.length ? riskFiles.map((item) => `- ${item}`) : ['- none detected'])
  ]);

  await updateWorkspaceProject(rootDir, {
    stack
  });

  await appendJsonl(path.join(paths.comprehensionDir, 'events.jsonl'), {
    ts: new Date().toISOString(),
    mode: profile.mode,
    since,
    project_id: profile.project_id,
    project_name: profile.project_name
  });

  await appendJsonl(path.join(paths.memoryDir, 'candidates.jsonl'), {
    ts: new Date().toISOString(),
    kind: 'project_comprehension',
    project_id: profile.project_id,
    summary: profile.summary,
    scopes: ['project_profile', 'module_map', 'commands', 'risk_files']
  });

  await logEvent(rootDir, 'run', 'comprehension.completed', {
    mode: profile.mode,
    since,
    project_id: profile.project_id,
    project_name: profile.project_name
  });

  return profile;
}

export async function incrementalComprehension(rootDir, since = null) {
  return fullComprehension(rootDir, { since });
}

export async function diffComprehension(rootDir, changeSummary = {}) {
  const paths = getWorkspacePaths(rootDir);
  await appendJsonl(path.join(paths.comprehensionDir, 'events.jsonl'), {
    ts: new Date().toISOString(),
    mode: 'diff',
    ...changeSummary
  });
  await logEvent(rootDir, 'run', 'comprehension.diff.completed', changeSummary);
  return changeSummary;
}
