package comprehension

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"moyuan-code/internal/fsutil"
	"moyuan-code/internal/logging"
	"moyuan-code/internal/textutil"
	"moyuan-code/internal/workspace"
)

type Entry struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type Stack struct {
	Languages       []string `json:"languages"`
	Frameworks      []string `json:"frameworks"`
	PackageManagers []string `json:"package_managers"`
	BuildCommands   []string `json:"build_commands"`
	TestCommands    []string `json:"test_commands"`
	LintCommands    []string `json:"lint_commands"`
}

type Profile struct {
	ProjectID       string         `json:"project_id"`
	ProjectName     string         `json:"project_name"`
	Root            string         `json:"root"`
	DetectedAt      string         `json:"detected_at"`
	Mode            string         `json:"mode"`
	Since           *string        `json:"since"`
	Stack           Stack          `json:"stack"`
	Repository      map[string]any `json:"repository"`
	TopLevelEntries []Entry        `json:"top_level_entries"`
	RiskFiles       []string       `json:"risk_files"`
	Summary         string         `json:"summary"`
}

func Full(ctx context.Context, rootDir string, since *string) (Profile, error) {
	_ = ctx
	ws, err := workspace.Load(rootDir)
	if err != nil {
		return Profile{}, err
	}
	stack := DetectStack(rootDir)
	entries := topEntries(rootDir)
	riskFiles := riskFiles(rootDir)
	mode := "full"
	if since != nil && *since != "" {
		mode = "incremental"
	}
	name := ws.Project.Project.Name
	projectID := ws.Project.Project.ID
	if projectID == "" {
		projectID = textutil.Slugify(name)
	}
	repoBytes, _ := json.Marshal(ws.Repository.Repository)
	repo := map[string]any{}
	_ = json.Unmarshal(repoBytes, &repo)
	profile := Profile{
		ProjectID:       projectID,
		ProjectName:     name,
		Root:            ws.Paths.RootDir,
		DetectedAt:      time.Now().UTC().Format(time.RFC3339Nano),
		Mode:            mode,
		Since:           since,
		Stack:           stack,
		Repository:      repo,
		TopLevelEntries: entries,
		RiskFiles:       riskFiles,
		Summary:         name + " project comprehension generated by Phase 1 Go control plane",
	}
	if err := writeArtifacts(ws.Paths, profile); err != nil {
		return Profile{}, err
	}
	ws.Project.Stack.Languages = stack.Languages
	ws.Project.Stack.Frameworks = stack.Frameworks
	ws.Project.Stack.PackageManagers = stack.PackageManagers
	ws.Project.Stack.BuildCommands = stack.BuildCommands
	ws.Project.Stack.TestCommands = stack.TestCommands
	ws.Project.Stack.LintCommands = stack.LintCommands
	if err := workspace.SaveProject(rootDir, ws.Project); err != nil {
		return Profile{}, err
	}
	_ = fsutil.AppendJSONL(filepath.Join(ws.Paths.ComprehensionDir, "events.jsonl"), map[string]any{
		"ts":           time.Now().UTC().Format(time.RFC3339Nano),
		"mode":         profile.Mode,
		"since":        since,
		"project_id":   profile.ProjectID,
		"project_name": profile.ProjectName,
	})
	_ = fsutil.AppendJSONL(filepath.Join(ws.Paths.MemoryDir, "candidates.jsonl"), map[string]any{
		"ts":         time.Now().UTC().Format(time.RFC3339Nano),
		"kind":       "project_comprehension",
		"project_id": profile.ProjectID,
		"summary":    profile.Summary,
		"scopes":     []string{"project_profile", "module_map", "commands", "risk_files"},
	})
	_ = logging.Log(rootDir, "run", "comprehension.completed", map[string]any{
		"mode":         profile.Mode,
		"since":        since,
		"project_id":   profile.ProjectID,
		"project_name": profile.ProjectName,
	})
	return profile, nil
}

func Incremental(ctx context.Context, rootDir string, since string) (Profile, error) {
	return Full(ctx, rootDir, &since)
}

func DetectStack(rootDir string) Stack {
	stack := Stack{
		Languages:       []string{},
		Frameworks:      []string{},
		PackageManagers: []string{},
		BuildCommands:   []string{},
		TestCommands:    []string{},
		LintCommands:    []string{},
	}
	for _, packageFile := range findStackFiles(rootDir, "package.json") {
		appendUnique(&stack.Languages, "TypeScript/JavaScript")
		appendUnique(&stack.PackageManagers, "npm")
		data, err := os.ReadFile(packageFile)
		if err == nil {
			var pkg struct {
				Scripts         map[string]string `json:"scripts"`
				Dependencies    map[string]string `json:"dependencies"`
				DevDependencies map[string]string `json:"devDependencies"`
			}
			if json.Unmarshal(data, &pkg) == nil {
				if pkg.Scripts["build"] != "" {
					appendUnique(&stack.BuildCommands, commandInDir(rootDir, packageFile, "npm run build"))
				}
				if pkg.Scripts["test"] != "" {
					appendUnique(&stack.TestCommands, commandInDir(rootDir, packageFile, "npm test"))
				}
				if pkg.Scripts["lint"] != "" {
					appendUnique(&stack.LintCommands, commandInDir(rootDir, packageFile, "npm run lint"))
				}
				detectFrameworks(&stack, pkg.Dependencies, pkg.DevDependencies)
			}
		}
	}
	if len(findStackFiles(rootDir, "pyproject.toml")) > 0 || len(findStackFiles(rootDir, "requirements.txt")) > 0 {
		appendUnique(&stack.Languages, "Python")
		appendUnique(&stack.PackageManagers, "pip/uv")
		for _, pyproject := range findStackFiles(rootDir, "pyproject.toml") {
			appendUnique(&stack.TestCommands, commandInDir(rootDir, pyproject, "python -m pytest"))
		}
	}
	for _, goMod := range findStackFiles(rootDir, "go.mod") {
		appendUnique(&stack.Languages, "Go")
		appendUnique(&stack.PackageManagers, "go")
		appendUnique(&stack.BuildCommands, commandInDir(rootDir, goMod, "go build ./..."))
		appendUnique(&stack.TestCommands, commandInDir(rootDir, goMod, "go test ./..."))
	}
	if len(stack.Languages) == 0 {
		stack.Languages = append(stack.Languages, "unknown")
	}
	return stack
}

func findStackFiles(rootDir string, filename string) []string {
	matches := []string{}
	rootDir = filepath.Clean(rootDir)
	_ = filepath.WalkDir(rootDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if entry.IsDir() {
			if path == rootDir {
				return nil
			}
			if skipStackDir(entry.Name()) {
				return filepath.SkipDir
			}
			rel, relErr := filepath.Rel(rootDir, path)
			if relErr == nil && pathDepth(rel) >= 3 {
				return filepath.SkipDir
			}
			return nil
		}
		if entry.Name() == filename {
			matches = append(matches, path)
		}
		return nil
	})
	sort.Strings(matches)
	return matches
}

func skipStackDir(name string) bool {
	if strings.HasPrefix(name, ".") {
		return true
	}
	switch name {
	case "node_modules", "dist", "build", "__pycache__", "venv", "skills":
		return true
	default:
		return false
	}
}

func pathDepth(rel string) int {
	if rel == "." || rel == "" {
		return 0
	}
	return len(strings.Split(filepath.ToSlash(rel), "/"))
}

func commandInDir(rootDir string, file string, command string) string {
	dir := filepath.Dir(file)
	rel, err := filepath.Rel(rootDir, dir)
	if err != nil || rel == "." {
		return command
	}
	return "cd " + filepath.ToSlash(rel) + " && " + command
}

func detectFrameworks(stack *Stack, dependencies map[string]string, devDependencies map[string]string) {
	hasDep := func(name string) bool {
		_, ok := dependencies[name]
		if ok {
			return true
		}
		_, ok = devDependencies[name]
		return ok
	}
	if hasDep("next") {
		appendUnique(&stack.Frameworks, "Next.js")
	}
	if hasDep("react") {
		appendUnique(&stack.Frameworks, "React")
	}
	if hasDep("vite") {
		appendUnique(&stack.Frameworks, "Vite")
	}
	if hasDep("vue") {
		appendUnique(&stack.Frameworks, "Vue")
	}
}

func appendUnique(items *[]string, value string) {
	value = strings.TrimSpace(value)
	if value == "" {
		return
	}
	for _, item := range *items {
		if item == value {
			return
		}
	}
	*items = append(*items, value)
}

func topEntries(rootDir string) []Entry {
	items, err := os.ReadDir(rootDir)
	if err != nil {
		return []Entry{}
	}
	entries := []Entry{}
	for _, item := range items {
		if strings.HasPrefix(item.Name(), ".") {
			continue
		}
		t := "file"
		if item.IsDir() {
			t = "directory"
		}
		entries = append(entries, Entry{Name: item.Name(), Type: t})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
	return entries
}

func riskFiles(rootDir string) []string {
	candidates := []string{".env", ".env.local", ".env.production", "package-lock.json", "pnpm-lock.yaml"}
	found := []string{}
	for _, candidate := range candidates {
		if fsutil.Exists(filepath.Join(rootDir, candidate)) {
			found = append(found, candidate)
		}
	}
	return found
}

func writeArtifacts(paths workspace.Paths, profile Profile) error {
	lines := []string{
		"# Project Profile",
		"",
		"- Project ID: `" + profile.ProjectID + "`",
		"- Project Name: `" + profile.ProjectName + "`",
		"- Root: `" + profile.Root + "`",
		"- Mode: `" + profile.Mode + "`",
		"- Languages: " + strings.Join(profile.Stack.Languages, ", "),
		"- Package Managers: " + orNone(profile.Stack.PackageManagers),
		"- Build Commands: " + orNone(profile.Stack.BuildCommands),
		"- Test Commands: " + orNone(profile.Stack.TestCommands),
		"- Lint Commands: " + orNone(profile.Stack.LintCommands),
		"- Risk Files: " + orNone(profile.RiskFiles),
		"",
	}
	if err := fsutil.WriteText(filepath.Join(paths.ComprehensionDir, "project-profile.md"), strings.Join(lines, "\n")); err != nil {
		return err
	}
	moduleLines := []string{"# Module Map", "", "## Top-Level Entries"}
	entryNames := map[string]bool{}
	for _, entry := range profile.TopLevelEntries {
		entryNames[entry.Name] = true
		moduleLines = append(moduleLines, "- "+entry.Type+": `"+entry.Name+"`")
	}
	moduleLines = append(moduleLines, "", "## Heuristic Responsibilities")
	responsibilities := []string{}
	if entryNames["frontend"] {
		responsibilities = append(responsibilities, "- `frontend/` indicates the user-facing web application surface.")
	}
	if entryNames["backend"] {
		responsibilities = append(responsibilities, "- `backend/` indicates server/API or data service code.")
	}
	if entryNames["skills"] {
		responsibilities = append(responsibilities, "- `skills/` indicates project-specific AI/tool skills.")
	}
	if entryNames["docs"] {
		responsibilities = append(responsibilities, "- `docs/` indicates design and documentation surfaces.")
	}
	if entryNames["scripts"] {
		responsibilities = append(responsibilities, "- `scripts/` indicates automation and helper entry points.")
	}
	if entryNames["cmd"] || entryNames["internal"] {
		responsibilities = append(responsibilities, "- `cmd/` and `internal/` indicate Go control plane code.")
	}
	if len(responsibilities) == 0 {
		responsibilities = append(responsibilities, "- No common module responsibilities detected yet.")
	}
	moduleLines = append(moduleLines, responsibilities...)
	if err := fsutil.WriteText(filepath.Join(paths.ComprehensionDir, "module-map.md"), strings.Join(moduleLines, "\n")+"\n"); err != nil {
		return err
	}
	commandLines := []string{"# Commands", "", "## Build"}
	commandLines = appendList(commandLines, profile.Stack.BuildCommands)
	commandLines = append(commandLines, "", "## Test")
	commandLines = appendList(commandLines, profile.Stack.TestCommands)
	commandLines = append(commandLines, "", "## Lint")
	commandLines = appendList(commandLines, profile.Stack.LintCommands)
	return fsutil.WriteText(filepath.Join(paths.ComprehensionDir, "commands.md"), strings.Join(commandLines, "\n")+"\n")
}

func orNone(items []string) string {
	if len(items) == 0 {
		return "none"
	}
	return strings.Join(items, ", ")
}

func appendList(lines []string, items []string) []string {
	if len(items) == 0 {
		return append(lines, "- none detected")
	}
	for _, item := range items {
		lines = append(lines, "- "+item)
	}
	return lines
}
